const fetchJobs = async () => {
    return [
      {
        title: "Software Developer",
        company_name: "TechCorp",
        location: "Remote",
        description: "Exciting opportunity to develop cutting-edge software for global clients.",
        url: "https://example.com/apply-software-developer",
      },
      {
        title: "Frontend Engineer",
        company_name: "Startup Inc.",
        location: "San Francisco, CA",
        description: "Design and implement user-facing features with React.",
        url: "https://example.com/apply-frontend-engineer",
      },
      {
        title: "Backend Developer",
        company_name: "Enterprise Solutions",
        location: "New York, NY",
        description: "Build scalable APIs and manage data flows for high-performance applications.",
        url: "https://example.com/apply-backend-developer",
      },
      {
        title: "Mobile App Developer",
        company_name: "App Innovations",
        location: "Los Angeles, CA",
        description: "Develop user-friendly mobile apps for iOS and Android platforms.",
        url: "https://example.com/apply-mobile-developer",
      },
      {
        title: "Data Scientist",
        company_name: "Analytics Pro",
        location: "Boston, MA",
        description: "Analyze large datasets to uncover insights and drive decision-making.",
        url: "https://example.com/apply-data-scientist",
      },
      {
        title: "UI/UX Designer",
        company_name: "Creative Labs",
        location: "Austin, TX",
        description: "Collaborate with developers to create stunning and user-friendly designs.",
        url: "https://example.com/apply-ui-ux-designer",
      },
      {
        title: "DevOps Engineer",
        company_name: "CloudTech",
        location: "Seattle, WA",
        description: "Implement CI/CD pipelines and manage cloud infrastructure.",
        url: "https://example.com/apply-devops-engineer",
      },
      {
        title: "Machine Learning Engineer",
        company_name: "AI Innovations",
        location: "Palo Alto, CA",
        description: "Develop and deploy machine learning models for cutting-edge applications.",
        url: "https://example.com/apply-ml-engineer",
      },
      {
        title: "Product Manager",
        company_name: "Visionary Products",
        location: "Chicago, IL",
        description: "Oversee product development and collaborate with cross-functional teams.",
        url: "https://example.com/apply-product-manager",
      },
      {
        title: "Cybersecurity Analyst",
        company_name: "Secure Solutions",
        location: "Washington, DC",
        description: "Protect company data by monitoring and responding to security threats.",
        url: "https://example.com/apply-cybersecurity-analyst",
      },
      {
        title: "Cloud Architect",
        company_name: "Global Cloud",
        location: "Denver, CO",
        description: "Design and implement cloud-based solutions to meet business needs.",
        url: "https://example.com/apply-cloud-architect",
      },
      {
        title: "Full Stack Developer",
        company_name: "Innovate LLC",
        location: "Atlanta, GA",
        description: "Work on both frontend and backend development for web applications.",
        url: "https://example.com/apply-fullstack-developer",
      },
      {
        title: "IT Support Specialist",
        company_name: "TechSupport Co.",
        location: "Philadelphia, PA",
        description: "Provide technical assistance and troubleshooting for end-users.",
        url: "https://example.com/apply-it-support-specialist",
      },
      {
        title: "Database Administrator",
        company_name: "DataCorp",
        location: "Phoenix, AZ",
        description: "Manage and optimize databases for efficient data storage and retrieval.",
        url: "https://example.com/apply-database-admin",
      },
      {
        title: "Game Developer",
        company_name: "Epic Games Studio",
        location: "Orlando, FL",
        description: "Create immersive gaming experiences using Unity and Unreal Engine.",
        url: "https://example.com/apply-game-developer",
      },
      {
        title: "AI Research Scientist",
        company_name: "DeepMind Tech",
        location: "Remote",
        description: "Conduct research in artificial intelligence to advance the state of the art.",
        url: "https://example.com/apply-ai-researcher",
      },
      {
        title: "Network Engineer",
        company_name: "NetSecure",
        location: "Dallas, TX",
        description: "Design, implement, and maintain reliable network systems.",
        url: "https://example.com/apply-network-engineer",
      },
      {
        title: "Blockchain Developer",
        company_name: "CryptoBuild",
        location: "Miami, FL",
        description: "Develop blockchain-based applications for secure transactions.",
        url: "https://example.com/apply-blockchain-developer",
      },
      {
        title: "Technical Writer",
        company_name: "DocsPro",
        location: "Portland, OR",
        description: "Create technical documentation and user guides for software products.",
        url: "https://example.com/apply-technical-writer",
      },
      {
        title: "Digital Marketing Specialist",
        company_name: "AdAgency Co.",
        location: "Las Vegas, NV",
        description: "Plan and execute digital marketing campaigns to grow brand awareness.",
        url: "https://example.com/apply-digital-marketing",
      },
    ];
  };
  
  export default fetchJobs;
  